### ISSUE TITLE
Basic Setup

### ISSUE THREAD

**Issue by aloukikomar** [abdullatheef/django_live_log#2]
[23/Apr/2019 12:50:46] "GET /dll/LOG/?file_path=/home/automation/webapps/AutoBox/BDD/Logs/TSR_1555668924/ HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django_live_log/views.py", line 21, in log_streamer
    yield t.render(Context({"result": result}))
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/usr/local/lib/python2.7/dist-packages/django/template/context.py", line 287, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than Context.

**Comment by aloukikomar** [comment]
can you please let me know what it means and what it was looking for

**Comment by latheef-tarams** [comment]
@aloukikomar

https://stackoverflow.com/questions/43787700/django-1-11-typeerror-context-must-be-a-dict-rather-than-context

This was done for django 1.7 . You may need to update code for latest version. Feel free to create PR. Will be updating myself when get time.

**Comment by latheef-tarams** [comment]
This has been fixed in https://github.com/abdullatheef/django_live_log/commit/8df27bcd73c81db5094aae4139295f5dd366fa6d

**Comment by abdullatheef** [comment]
This has been fixed in https://github.com/abdullatheef/django_live_log/commit/8df27bcd73c81db5094aae4139295f5dd366fa6d

**Comment by aloukikomar** [comment]
Thanks man ,the changes helped ..!!
